name: Schedule run of hq.py
# on: push
on:
  schedule:
    - cron: '21 1 * * *'
env:
  PRO_USER_NAME: ${{ secrets.PRO_USER_NAME }}
  PRO_USER_PASSWORD: ${{ secrets.PRO_USER_PASSWORD }}
  REGISTRANT_USER_NAME: ${{ secrets.REGISTRANT_USER_NAME }}
  REGISTRANT_USER_PASSWORD: ${{ secrets.REGISTRANT_USER_PASSWORD }}

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Activate virtual environment and install uv
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install uv

      - name: Install dependencies with uv
        run: |
          source .venv/bin/activate
          uv sync
          python -m playwright install

      - name: Run hq.py
        run: |
          source .venv/bin/activate
          python date_variables.py
          # python hq.py
          # python case_register.py
          # python verify_secrets_accessible.py
